development:
  adapter: postgresql
  encoding: unicode
  database: backbone_development
  pool: 5
  username: earlynovrock
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: backbone_test
  pool: 5
  username: earlynovrock
  password: